name: "Publish package"

on:
  release:
    types:
      - "published"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: "Install packages"
        run: npm ci
      - name: "Audit production dependencies"
        run: npm audit --omit=dev --audit-level=high
      - name: "Run all tests"
        run: npm test
      - name: "Build package"
        run: npm run build
      - name: "Publish package"
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
