name: "Publish package"

on:
  release:
    types:
      - "published"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Use Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
      - name: "Install packages"
        run: npm install
      - name: "Build package"
        run: npm run build
      - name: "Publish package"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
