name: "Test package"

on:
  pull_request:
    branches:
      - "master"
      - "1.x"
    types:
      - "opened"
      - "synchronize"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: "Install npm"
        run: npm ci
      - name: "Audit production dependencies"
        run: npm audit --omit=dev --audit-level=high
      - name: "Run all tests"
        run: npm run test
